In [1]:
import pandas as pd

df = pd.read_csv("../data/df_Payments.csv")
df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

In [2]:
df.shape

(89316, 5)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  object
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  object
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.4+ MB

In [4]:
df.describe(include="all")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,89316,89316.000000,89316,89316.000000,89316.000000
unique,89316,NaN,4,NaN,NaN
top,Axfy13Hk4PIk,NaN,credit_card,NaN,NaN
freq,1,NaN,65814,NaN,NaN
mean,NaN,1.099646,NaN,2.965717,268.657190
std,NaN,0.772658,NaN,2.796406,344.409566
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,84.340000
50%,NaN,1.000000,NaN,2.000000,171.860000
75%,NaN,1.000000,NaN,4.000000,313.530000
max,NaN,29.000000,NaN,24.000000,7274.880000

In [5]:
df.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [8]:
df.to_csv(
    "cleaned_payments.csv",
    index=False
)