In [4]:
import pandas as pd

df = pd.read_csv("../data/df_Customers.csv")
df.head()

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP

In [5]:
df.shape

(89316, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  object
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  object
 3   customer_state            89316 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.7+ MB

In [7]:
df.describe(include="all")

         customer_id  customer_zip_code_prefix customer_city customer_state
count          89316              89316.000000         89316          89316
unique         89316                       NaN          3735             27
top     hCT0x9JiGXBQ                       NaN     sao paulo             SP
freq               1                       NaN         14352          37879
mean             NaN              40499.471080           NaN            NaN
std              NaN              31194.386361           NaN            NaN
min              NaN               1003.000000           NaN            NaN
25%              NaN               9785.000000           NaN            NaN
50%              NaN              35480.000000           NaN            NaN
75%              NaN              70040.000000           NaN            NaN
max              NaN              99990.000000           NaN            NaN

In [8]:
df.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
print((df == '?').sum())

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [11]:
df["customer_id"].duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

customer_id                 object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [13]:
df["customer_state"].unique()

array(['SP', 'RJ', 'MG', 'SC', 'ES', 'RN', 'BA', 'DF', 'RS', 'PE', 'GO',
       'CE', 'PR', 'MA', 'PI', 'MT', 'MS', 'SE', 'RO', 'TO', 'AM', 'AP',
       'PB', 'PA', 'AL', 'AC', 'RR'], dtype=object)

In [14]:
df["customer_state"].value_counts()

customer_state
SP    37879
RJ    11578
MG    10334
RS     4921
PR     4523
SC     3213
BA     3088
GO     1868
ES     1798
DF     1793
PE     1493
CE     1141
MT      848
PA      817
MS      637
MA      623
PB      497
PI      423
RN      381
AL      342
SE      305
TO      247
RO      241
AM      140
AC       75
AP       68
RR       43
Name: count, dtype: int64

In [15]:
df["customer_city"].value_counts()

customer_city
sao paulo          14352
rio de janeiro      6248
belo horizonte      2426
brasilia            1778
curitiba            1421
                   ...
sambaiba               1
lagoa dos patos        1
jacuipe                1
terezinha              1
macuco de minas        1
Name: count, Length: 3735, dtype: int64

In [17]:
df["customer_zip_code_prefix"] = (
    df["customer_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [18]:
df["customer_zip_code_prefix"].astype(str).str.len().value_counts()

customer_zip_code_prefix
5    89316
Name: count, dtype: int64

In [20]:
df["customer_city"] = df["customer_city"].fillna("Unknown")

In [21]:
df.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df["customer_id"].duplicated().sum()

np.int64(0)

In [24]:
df.dtypes

customer_id                 object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [25]:
df["customer_zip_code_prefix"].astype(str).str.len().value_counts()

customer_zip_code_prefix
5    89316
Name: count, dtype: int64

In [27]:
df.to_csv(
    "cleaned_customers.csv",
    index=False
)