In [1]:
import pandas as pd

df = pd.read_csv("../data/df_OrderItems.csv")
df.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [2]:
df.shape

(89316, 5)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  object
 1   product_id        89316 non-null  object
 2   seller_id         89316 non-null  object
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), object(3)
memory usage: 3.4+ MB

In [4]:
df.describe(include="all")

,order_id,product_id,seller_id,price,shipping_charges
count,89316,89316,89316,89316.000000,89316.000000
unique,89316,27451,2929,NaN,NaN
top,Axfy13Hk4PIk,0vbEvli2JYJu,RKad98cTxhSb,NaN,NaN
freq,1,405,1657,NaN,NaN
mean,NaN,NaN,NaN,340.900543,44.283210
std,NaN,NaN,NaN,557.459897,37.672491
min,NaN,NaN,NaN,0.850000,0.000000
25%,NaN,NaN,NaN,59.650000,20.110000
50%,NaN,NaN,NaN,136.900000,35.055000
75%,NaN,NaN,NaN,399.200000,57.190000
max,NaN,NaN,NaN,6735.000000,409.680000

In [5]:
df.isnull().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.to_csv(
    "cleaned_orderitems.csv",
    index=False
)